//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Serialization;

namespace MHGameWork.TheWizards.CG.SDL
{ // 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Sdl {
    
        private Camera[] camerasField;
    
        private Lights lightsField;
    
        private Geometry geometryField;
    
        private Texture[] texturesField;
    
        private Materials materialsField;
    
        private Scene sceneField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Camera", IsNullable=false)]
        public Camera[] Cameras {
            get {
                return this.camerasField;
            }
            set {
                this.camerasField = value;
            }
        }
    
        /// <remarks/>
        public Lights Lights {
            get {
                return this.lightsField;
            }
            set {
                this.lightsField = value;
            }
        }
    
        /// <remarks/>
        public Geometry Geometry {
            get {
                return this.geometryField;
            }
            set {
                this.geometryField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Texture", IsNullable=false)]
        public Texture[] Textures {
            get {
                return this.texturesField;
            }
            set {
                this.texturesField = value;
            }
        }
    
        /// <remarks/>
        public Materials Materials {
            get {
                return this.materialsField;
            }
            set {
                this.materialsField = value;
            }
        }
    
        /// <remarks/>
        public Scene Scene {
            get {
                return this.sceneField;
            }
            set {
                this.sceneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Camera {
    
        private string positionField;
    
        private string directionField;
    
        private string upField;
    
        private string fovyField;
    
        private string nameField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string up {
            get {
                return this.upField;
            }
            set {
                this.upField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fovy {
            get {
                return this.fovyField;
            }
            set {
                this.fovyField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Lights {
    
        private object[] itemsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DirectionalLight", typeof(DirectionalLight))]
        [System.Xml.Serialization.XmlElementAttribute("PointLight", typeof(PointLight))]
        [System.Xml.Serialization.XmlElementAttribute("SpotLight", typeof(SpotLight))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class DirectionalLight {
    
        private string directionField;
    
        private string intensityField;
    
        private string colorField;
    
        private string nameField;
    
        public DirectionalLight() {
            this.intensityField = "1";
            this.colorField = "1 1 1";
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string intensity {
            get {
                return this.intensityField;
            }
            set {
                this.intensityField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1 1 1")]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class PointLight {
    
        private string positionField;
    
        private string intensityField;
    
        private string colorField;
    
        private string nameField;
    
        public PointLight() {
            this.intensityField = "1";
            this.colorField = "1 1 1";
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string intensity {
            get {
                return this.intensityField;
            }
            set {
                this.intensityField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1 1 1")]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class SpotLight {
    
        private string positionField;
    
        private string directionField;
    
        private string angleField;
    
        private string intensityField;
    
        private string colorField;
    
        private string nameField;
    
        public SpotLight() {
            this.intensityField = "1";
            this.colorField = "1 1 1";
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string intensity {
            get {
                return this.intensityField;
            }
            set {
                this.intensityField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1 1 1")]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Geometry {
    
        private object[] itemsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cone", typeof(Cone))]
        [System.Xml.Serialization.XmlElementAttribute("Cylinder", typeof(Cylinder))]
        [System.Xml.Serialization.XmlElementAttribute("IndexedTriangleSet", typeof(IndexedTriangleSet))]
        [System.Xml.Serialization.XmlElementAttribute("Sphere", typeof(Sphere))]
        [System.Xml.Serialization.XmlElementAttribute("Teapot", typeof(Teapot))]
        [System.Xml.Serialization.XmlElementAttribute("Torus", typeof(Torus))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Cone {
    
        private string radiusField;
    
        private string heightField;
    
        private ConeCapped cappedField;
    
        private string nameField;
    
        public Cone() {
            this.cappedField = ConeCapped.@true;
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ConeCapped.@true)]
        public ConeCapped capped {
            get {
                return this.cappedField;
            }
            set {
                this.cappedField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    public enum ConeCapped {
    
        /// <remarks/>
        @true,
    
        /// <remarks/>
        @false,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Cylinder {
    
        private string radiusField;
    
        private string heightField;
    
        private CylinderCapped cappedField;
    
        private string nameField;
    
        public Cylinder() {
            this.cappedField = CylinderCapped.@true;
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CylinderCapped.@true)]
        public CylinderCapped capped {
            get {
                return this.cappedField;
            }
            set {
                this.cappedField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    public enum CylinderCapped {
    
        /// <remarks/>
        @true,
    
        /// <remarks/>
        @false,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class IndexedTriangleSet {
    
        private string coordinatesField;
    
        private string normalsField;
    
        private string textureCoordinatesField;
    
        private string coordinateIndicesField;
    
        private string normalIndicesField;
    
        private string textureCoordinateIndicesField;
    
        private string nameField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string normals {
            get {
                return this.normalsField;
            }
            set {
                this.normalsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string textureCoordinates {
            get {
                return this.textureCoordinatesField;
            }
            set {
                this.textureCoordinatesField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coordinateIndices {
            get {
                return this.coordinateIndicesField;
            }
            set {
                this.coordinateIndicesField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string normalIndices {
            get {
                return this.normalIndicesField;
            }
            set {
                this.normalIndicesField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string textureCoordinateIndices {
            get {
                return this.textureCoordinateIndicesField;
            }
            set {
                this.textureCoordinateIndicesField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Sphere {
    
        private string radiusField;
    
        private string nameField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Teapot {
    
        private string sizeField;
    
        private string nameField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Torus {
    
        private string innerRadiusField;
    
        private string outerRadiusField;
    
        private string nameField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string innerRadius {
            get {
                return this.innerRadiusField;
            }
            set {
                this.innerRadiusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outerRadius {
            get {
                return this.outerRadiusField;
            }
            set {
                this.outerRadiusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Texture {
    
        private string srcField;
    
        private string nameField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Materials {
    
        private object[] itemsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DiffuseMaterial", typeof(DiffuseMaterial))]
        [System.Xml.Serialization.XmlElementAttribute("LinearCombinedMaterial", typeof(LinearCombinedMaterial))]
        [System.Xml.Serialization.XmlElementAttribute("PhongMaterial", typeof(PhongMaterial))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class DiffuseMaterial {
    
        private string colorField;
    
        private string nameField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class LinearCombinedMaterial {
    
        private string material1Field;
    
        private string weight1Field;
    
        private string material2Field;
    
        private string weight2Field;
    
        private string nameField;
    
        public LinearCombinedMaterial() {
            this.weight1Field = "0.5";
            this.weight2Field = "0.5";
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string material1 {
            get {
                return this.material1Field;
            }
            set {
                this.material1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0.5")]
        public string weight1 {
            get {
                return this.weight1Field;
            }
            set {
                this.weight1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string material2 {
            get {
                return this.material2Field;
            }
            set {
                this.material2Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0.5")]
        public string weight2 {
            get {
                return this.weight2Field;
            }
            set {
                this.weight2Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class PhongMaterial {
    
        private string colorField;
    
        private string shininessField;
    
        private string nameField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shininess {
            get {
                return this.shininessField;
            }
            set {
                this.shininessField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Scene {
    
        private object[] itemsField;
    
        private string cameraField;
    
        private string lightsField;
    
        private string backgroundField;
    
        public Scene() {
            this.backgroundField = "0 0 0";
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rotate", typeof(Rotate))]
        [System.Xml.Serialization.XmlElementAttribute("Scale", typeof(Scale))]
        [System.Xml.Serialization.XmlElementAttribute("Shape", typeof(Shape))]
        [System.Xml.Serialization.XmlElementAttribute("Translate", typeof(Translate))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string camera {
            get {
                return this.cameraField;
            }
            set {
                this.cameraField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lights {
            get {
                return this.lightsField;
            }
            set {
                this.lightsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0 0 0")]
        public string background {
            get {
                return this.backgroundField;
            }
            set {
                this.backgroundField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Rotate {
    
        private object[] itemsField;
    
        private string axisField;
    
        private string angleField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rotate", typeof(Rotate))]
        [System.Xml.Serialization.XmlElementAttribute("Scale", typeof(Scale))]
        [System.Xml.Serialization.XmlElementAttribute("Shape", typeof(Shape))]
        [System.Xml.Serialization.XmlElementAttribute("Translate", typeof(Translate))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string axis {
            get {
                return this.axisField;
            }
            set {
                this.axisField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Scale {
    
        private object[] itemsField;
    
        private string scaleField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rotate", typeof(Rotate))]
        [System.Xml.Serialization.XmlElementAttribute("Scale", typeof(Scale))]
        [System.Xml.Serialization.XmlElementAttribute("Shape", typeof(Shape))]
        [System.Xml.Serialization.XmlElementAttribute("Translate", typeof(Translate))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Shape {
    
        private string geometryField;
    
        private string materialField;
    
        private string textureField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string geometry {
            get {
                return this.geometryField;
            }
            set {
                this.geometryField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string texture {
            get {
                return this.textureField;
            }
            set {
                this.textureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Translate {
    
        private object[] itemsField;
    
        private string vectorField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rotate", typeof(Rotate))]
        [System.Xml.Serialization.XmlElementAttribute("Scale", typeof(Scale))]
        [System.Xml.Serialization.XmlElementAttribute("Shape", typeof(Shape))]
        [System.Xml.Serialization.XmlElementAttribute("Translate", typeof(Translate))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vector {
            get {
                return this.vectorField;
            }
            set {
                this.vectorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Cameras {
    
        private Camera[] cameraField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Camera")]
        public Camera[] Camera {
            get {
                return this.cameraField;
            }
            set {
                this.cameraField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdl", IsNullable=false)]
    public partial class Textures {
    
        private Texture[] textureField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Texture")]
        public Texture[] Texture {
            get {
                return this.textureField;
            }
            set {
                this.textureField = value;
            }
        }
    }
}