cd ..

rmdir /S /Q "bin/Binaries"
rmdir /S /Q "bin/Cache"

rmdir /S /Q "ApplicationLogic/bin"
rmdir /S /Q "Client/bin"
rmdir /S /Q "ColladaSchema/bin"
rmdir /S /Q "Common.Core/bin"
rmdir /S /Q "DirectX10/bin"
rmdir /S /Q "DirectX11/bin"
rmdir /S /Q "Editor/bin"
rmdir /S /Q "Gameplay/bin"
rmdir /S /Q "GUI/bin"
rmdir /S /Q "Launcher/bin"
rmdir /S /Q "Networking/bin"
rmdir /S /Q "NewModules/bin"
rmdir /S /Q "ProceduralTerrainGeneration/bin"
rmdir /S /Q "Server/bin"
rmdir /S /Q "ServerClient/bin"
rmdir /S /Q "TestRunner/bin"
rmdir /S /Q "TileEngine/bin"
rmdir /S /Q "TreeGenerator/bin"
rmdir /S /Q "Unit Tests/bin"

rmdir /S /Q "ApplicationLogic/obj"
rmdir /S /Q "Client/obj"
rmdir /S /Q "ColladaSchema/obj"
rmdir /S /Q "Common.Core/obj"
rmdir /S /Q "DirectX10/obj"
rmdir /S /Q "DirectX11/obj"
rmdir /S /Q "Editor/obj"
rmdir /S /Q "Gameplay/obj"
rmdir /S /Q "GUI/obj"
rmdir /S /Q "Launcher/obj"
rmdir /S /Q "Networking/obj"
rmdir /S /Q "NewModules/obj"
rmdir /S /Q "ProceduralTerrainGeneration/obj"
rmdir /S /Q "Server/obj"
rmdir /S /Q "ServerClient/obj"
rmdir /S /Q "TestRunner/obj"
rmdir /S /Q "TileEngine/obj"
rmdir /S /Q "TreeGenerator/obj"
rmdir /S /Q "Unit Tests/obj"

rmdir /S /Q "AdminClientVB/bin"
rmdir /S /Q "ClientVB/bin"
rmdir /S /Q "Common/bin"
rmdir /S /Q "Common.NetworkingVB/bin"
rmdir /S /Q "CommonVB/bin"
rmdir /S /Q "CoreFileUpdater/bin"
rmdir /S /Q "Game3DPlay/bin"
rmdir /S /Q "NovodexWrapperXNA/bin"
rmdir /S /Q "ServerClientOud/bin"

rmdir /S /Q "AdminClientVB/obj"
rmdir /S /Q "ClientVB/obj"
rmdir /S /Q "Common/obj"
rmdir /S /Q "Common.NetworkingVB/obj"
rmdir /S /Q "CommonVB/obj"
rmdir /S /Q "CoreFileUpdater/obj"
rmdir /S /Q "Game3DPlay/obj"
rmdir /S /Q "NovodexWrapperXNA/obj"
rmdir /S /Q "ServerClientOud/obj"